name: Preview Image

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Publish browser branch preview
    steps:
      - uses: actions/checkout@v2
      - uses: hpi-swa/setup-smalltalkCI@v1
        with:
          smalltalk-image: Squeak64-5.3
      - run: smalltalkci -s 'Squeak64-5.3' || true
        shell: bash
        timeout-minutes: 15
        env:
          # for uploading coverage reports
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v3
        with:
          repository: ko-redtruck/SqueakJS
          path: SqueakJS
      - run: cp $SMALLTALK_CI_BUILD/TravisCI.* ./SqueakJS/
      - uses: amondnet/vercel-action@v20 #deploy
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          github-token: ${{ secrets.GITHUB_TOKEN }} #Optional 
          vercel-org-id: ${{ secrets.ORG_ID}}  #Required
          vercel-project-id: ${{ secrets.PROJECT_ID}} #Required 
          working-directory: ./SqueakJS
